name: Build Hugo and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
      
      # - name: Build Hugo for Aliyun OSS
      #   run: |
      #     hugo --minify --enableGitInfo --baseURL "https://www.qladgk.com/" --destination ./public-aliyun-oss

      - name: Build Hugo for GitHub Pages
        run: |
          hugo --minify --enableGitInfo --baseURL "https://qlad.github.io/" --destination ./public-gh-pages

      - name: Build Hugo for Cloudflare Pages
        run: |
          hugo --minify --enableGitInfo --baseURL "https://qladgk.pages.dev/" --destination ./public-cf-pages

      - name: Publish Site to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public-gh-pages

      - name: Publish to Cloudflare Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          quiet: true
          command: pages deploy ./public-cf-pages --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} --commit-dirty=true

      # - name: Deploy to Aliyun OSS
      #   uses: docker://fangbinwei/aliyun-oss-website-action:v1
      #   env:
      #     ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      #     ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
      #     BUCKET: qladgk-com
      #     ENDPOINT: oss-cn-hongkong.aliyuncs.com
      #     FOLDER: public-aliyun-oss
      #     SKIP_SETTING: true
      #     INCREMENTAL: true