name: Submit Sitemap to Baidu

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  submit-baidu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          pip3 install lxml

      - name: Submit to Baidu
        run: |
          if [ -f public/zh-cn/sitemap.xml ]; then
            cp public/zh-cn/sitemap.xml scripts;
            cd scripts;
            python3 baidu.py sitemap.xml "${{ secrets.BAIDU_API_URL }}";
          else
            echo "Error: sitemap.xml not found!";
            exit 1;
          fi
