name: Submit URLs to Baidu

on:
  # schedule:
  #   - cron: "0 0 * * *"  # 每天早上 8:00 上海时间（UTC+8）
  workflow_dispatch:     # 手动触发

jobs:
  submit-urls:
    runs-on: ubuntu-latest

    steps:
      # 检出主分支的代码
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      # 检出 gh-pages 分支的代码到指定目录
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: public

      # 设置运行脚本需要的权限
      - name: Set execute permission
        run: chmod +x scripts/submit_urls.sh

      # 运行脚本，提交 URL 到 Baidu
      - name: Submit URLs to Baidu
        env:
          BAIDU_API_URL: ${{ secrets.BAIDU_API_URL }}
        run: scripts/submit_urls.sh
