name: Sync Mastodon Status

on:
  #  schedule:
  #  - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  sync-mastodon:
    name: Fetch mastodon status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check JQ
        run: |
          if ! command -v jq &> /dev/null; then
            echo "jq is not installed. Installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          else
            echo "jq is already installed."
          fi
          echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Download Mastodon Status
        run: |
          cd assets/data/mastodon/
          rm mastodon.json
          url="https://mastodon.social/api/v1/accounts/113099580562756061/statuses?limit=20&exclude_replies=true&exclude_reblogs=true"
          output="mastodon.json"
          curl -s "$url" >"$output"
          echo "TAG_NAME=$(jq -r '.[0].tags[0].name' mastodon.json)" >> $GITHUB_ENV

      - name: Git Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(data): fetch mastodon status"
          committer_name: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          add: |
            './assets/data/mastodon/mastodon.json'
